"""Change password column in User model

Revision ID: 31a4111afe41
Revises: 8e800b625e90
Create Date: 2024-05-06 23:34:43.634180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a4111afe41'
down_revision: Union[str, None] = '8e800b625e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash', new_column_name='password', existing_type=sa.String(length=255), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', new_column_name='password_hash', existing_type=sa.String(length=255), existing_nullable=False)

